### ISSUE TITLE
Any particular reason why stat is not exposed?

### ISSUE THREAD

**Issue by ahmetb** [sbinet/pstree#1]
Is there a reason to why not to expose the full stat https://github.com/sbinet/pstree/blob/cacb7032c7496c1b4f88b71eb2dd54928c8640ab/pstree.go#L124-L128 but rather just `pid` and `ppid`?

**Comment by sbinet** [comment]
it was mainly because I just needed these to build the tree of processes.

I could accept a PR with, say, `Process` gaining fields from the full `stat`.

**Comment by ahmetb** [comment]
Yeah I found this project much simpler than other procfs readers because it constructed the FS tree for me. I already have a PR ready, will send.

**Comment by sbinet** [comment]
fixed by #2
